In [10]:
import numpy as np 
import pandas as pd

In [59]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[4],[5],[7]])
print(x,y)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[4]
 [5]
 [7]]


In [60]:
class regresion:
  def __init__(self,matriz_y,matriz_x):
    self.matriz_y=matriz_y
    self.matriz_x=matriz_x
  def matriz_x(self):
    if self.matriz_x==np.ndarray:
       print("esta correcta la matriz x")
    else:
      print("ingresar una matriz valida")
  def matriz_y(self):
    if self.matriz_x==np.ndarray:
      print("esta correcta la matriz y")
    else:
      print("ingrese una matriz valida")
  def coefi1(self):
    betas=np.linalg.inv(self.matriz_x.T @ self.matriz_x) @ self.matriz_x.T @ self.matriz_y
    print(betas)



In [61]:
intento_1= regresion(y,x)

In [62]:
intento_1.coefi1()

[[-1.984375 ]
 [ 0.       ]
 [ 1.9609375]]
